name: android-release
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk-local
      ANDROID_HOME:     ${{ runner.temp }}/android-sdk-local
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'     # wichtig: breit kompatibel (AGP/Gradle)

      - name: Build (local SDK + Capacitor + Gradle)
        run: |
          set -euxo pipefail
          bash -x ci-build-android.sh 2>&1 | tee buildlog.txt

      - name: Upload APK artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: artifacts/**
          if-no-files-found: warn

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: buildlog.txt
          if-no-files-found: warn
