name: android-debug
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Install Android SDK (cmdline-tools)
        run: |
          ANDROID_SDK_ROOT="$HOME/Android/Sdk"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd /tmp
          curl -sSLo cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest"/ || true
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Install deps & web build
        run: |
          npm ci
          npm run build

      - name: Add + Sync Android (Capacitor)
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build debug APK
        run: |
          cd android
          ./gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
