name: android-apk
on:
  workflow_dispatch:
  push:
    paths:
      - "android/**"
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.*"
      - "capacitor.config.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Build web assets
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: "34.0.0"
          components: platform-tools

      - name: Ensure Capacitor Android project & sync
        run: |
          npm i -D @capacitor/cli
          npm i @capacitor/core
          npx cap sync android

      - name: Write local.properties (SDK path)
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Assemble release APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-dist
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
