name: android-debug
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Android SDK
        run: |
          export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd /tmp
          curl -LO https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-*_latest.zip
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv -f cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Web build & Capacitor sync
        run: |
          npm ci
          npm run build
          npx cap add android || true
          npx cap sync android

      - name: Assemble debug APK
        run: ./android/gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
