name: tests
on: [push, pull_request]

# Verhindert doppelte Builds pro Branch (bricht ältere ab)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Buddy UT CLI robust installieren (nicht-fatal) + in PATH
      - name: Install Buddy UT CLI (non-fatal)
        run: |
          set -e
          if ! command -v bdy >/dev/null 2>&1; then
            curl -fsSL https://es.buddy.works/bdy/install.sh | bash || true
            echo "$HOME/.buddy/bin" >> "$GITHUB_PATH" || true
          fi
          bdy --version || echo "bdy not found (non-fatal)"

      - name: Free 8080 (just in case)
        run: sudo fuser -k 8080/tcp || true

      - run: npm ci || npm i

      - name: Install Cypress deps
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Cypress-Binary cachen (beschleunigt Folge-Builds)
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Vitest + Upload
        env:
          BUDDY_UT_TOKEN: ${{ secrets.BUDDY_UT_TOKEN }}
        run: npm run test:ci

      - name: Cypress + Upload
        env:
          BUDDY_UT_TOKEN: ${{ secrets.BUDDY_UT_TOKEN }}
        run: npm run cy:ci

      # JUnit immer hochladen (auch bei Fail)
      - name: Upload JUnit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/*.xml
          if-no-files-found: warn

      # Bei Fehlschlag: Screenshots/Videos sichern
      - name: Upload Cypress screenshots (on fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*
          if-no-files-found: ignore

      - name: Upload Cypress videos (on fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*
          if-no-files-found: ignore
