
name: tests

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions: { contents: read }

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      NODE_VERSION: '22'
      PORT: '5173'
      ELECTRON_DISABLE_GPU: '1'
      DBUS_SESSION_BUS_ADDRESS: '/dev/null'
      NO_AT_BRIDGE: '1'
      TERM: 'xterm'
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install system deps (xvfb, lsof)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb lsof

      - name: Install deps
        run: npm ci || npm i

      - name: Run Vitest (JUnit)
        run: |
          mkdir -p reports
          npx vitest run --reporter=junit --outputFile=reports/junit.xml || true

      - name: Run Cypress (Electron, headless) – PORT Fix
        env:
          PORT: ${{ env.PORT }}
        run: |
          set -e
          PORT="${PORT:-5173}"
          npx kill-port "$PORT" || true
          npx --yes start-server-and-test \
            "npm run dev -- --port $PORT --strictPort" \
            "http://127.0.0.1:$PORT/@vite/client" \
            "xvfb-run -a npx cypress run --e2e --browser electron"

      - name: Upload JUnit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/**/*.xml
          if-no-files-found: warn

      - name: Buddy upload (only if secret exists)
        if: ${{ secrets.BUDDY_UT_TOKEN }}
        env:
          BUDDY_UT_TOKEN: ${{ secrets.BUDDY_UT_TOKEN }}
        run: |
          set -euo pipefail
          echo "Buddy token present: $([ -n "${BUDDY_UT_TOKEN:-}" ] && echo yes || echo no)"
          if ! command -v bdy >/dev/null 2>&1; then
            echo "deb [trusted=yes] https://es.buddy.works/bdy/apt-repo prod main" | sudo tee /etc/apt/sources.list.d/bdy.list >/dev/null
            sudo apt-get update -y
            sudo apt-get install -y bdy
          fi
          shopt -s nullglob
          for f in reports/*.xml; do
            echo "Buddy upload: $f"
            bdy tests upload --format junit-xml "$f" || echo "WARN: Buddy-Upload fehlgeschlagen für $f"
          done
          set -e
          PORT="${PORT:-5173}"
          npx kill-port "$PORT" || true
          npx --yes start-server-and-test \
            "npm run dev -- --port $PORT --strictPort" \
            "http://127.0.0.1:$PORT/@vite/client" \
            "xvfb-run -a npx cypress run --e2e --browser electron"

      - name: Upload JUnit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/**/*.xml
          if-no-files-found: warn

      - name: Buddy upload (only if secret exists)
        if: ${{ secrets.BUDDY_UT_TOKEN }}
        env:
          BUDDY_UT_TOKEN: ${{ secrets.BUDDY_UT_TOKEN }}
        run: |
          set -euo pipefail
          echo "Buddy token present: $([ -n "${BUDDY_UT_TOKEN:-}" ] && echo yes || echo no)"
          if ! command -v bdy >/dev/null 2>&1; then
            echo "deb [trusted=yes] https://es.buddy.works/bdy/apt-repo prod main" | sudo tee /etc/apt/sources.list.d/bdy.list >/dev/null
            sudo apt-get update -y
            sudo apt-get install -y bdy
          fi
          shopt -s nullglob
          for f in reports/*.xml; do
            echo "Buddy upload: $f"
            bdy tests upload --format junit-xml "$f" || echo "WARN: Buddy-Upload fehlgeschlagen für $f"
          done
