name: tests

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions: { contents: read }

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      NODE_VERSION: '22'
      PORT: '8080'
      ELECTRON_DISABLE_GPU: '1'
      DBUS_SESSION_BUS_ADDRESS: '/dev/null'
      NO_AT_BRIDGE: '1'
      TERM: 'xterm'
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # Cache für Cypress-Binary (schnellere Runs)
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install deps
        run: npm ci || npm i

      - name: Run Vitest (JUnit)
        run: |
          mkdir -p reports
          npx --yes vitest run --reporter=junit --outputFile=reports/junit.xml

      - name: Install system deps (xvfb)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb

      - name: Cypress e2e (Electron, headless) -> JUnit
        env:
          PORT: ${{ env.PORT }}
        run: |
          mkdir -p reports
          # dev-server starten & warten bis /@vite/client 200 liefert, dann Cypress headless laufen lassen
          npx --yes start-server-and-test \
            "npm run dev -- --port $PORT --strictPort" \
            "http://127.0.0.1:$PORT/@vite/client" \
            "xvfb-run -a npx cypress run --e2e --browser electron --reporter junit --reporter-options mochaFile=reports/cypress-[hash].xml,toConsole=false"

      - name: Upload JUnit artifacts (Vitest + Cypress)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/*.xml
          if-no-files-found: warn

      # Optional – nur wenn Secret BUDDY_UT_TOKEN gesetzt ist
      - name: Buddy upload (optional)
        if: always()
        env:
          BUDDY_UT_TOKEN: ${{ secrets.BUDDY_UT_TOKEN }}
        run: |
          set -euo pipefail
          if ! command -v bdy >/dev/null 2>&1; then
            echo "deb [trusted=yes] https://es.buddy.works/bdy/apt-repo prod main" | sudo tee /etc/apt/sources.list.d/bdy.list >/dev/null
            sudo apt-get update -y
            sudo apt-get install -y bdy
          fi
          bdy --version || true
          shopt -s nullglob
          for f in reports/*.xml; do
            echo "Buddy: $f"
            bdy tests upload --format junit-xml "$f" || true
          done
